# Generated by Django 4.1.2 on 2022-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofbook', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(upload_to='photosfolder/%y/%m/%d')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
