# Generated by Django 4.1.2 on 2022-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'my books'},
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, choices=[('horror', 'horror'), ('action', 'action'), ('comedy', 'comedy'), ('effects and ambiguity', 'effects and ambiguity'), ('drama', 'drama')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='a description'),
        ),
        migrations.AlterField(
            model_name='books',
            name='images',
            field=models.ImageField(default='photosfolder/22/11/22/pexels1.jpg', upload_to='photosfolder/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='books',
            name='nameofbook',
            field=models.CharField(max_length=10),
        ),
    ]
