# Generated by Django 4.1.2 on 2022-11-22 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_books_options_books_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Auto_post_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='books',
            name='Production_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='books',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
